# Run ansible lint https://ansible-lint.readthedocs.io/en/latest/configuring.html
- repo: https://github.com/ansible-community/ansible-lint.git
  rev: v5.1.3 # put latest release tag from https://github.com/ansible-community/ansible-lint/releases/
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
