---
# Built from docs https://yamllint.readthedocs.io/en/stable/configuration.html
extends: default

# Directories and Files to ignore
ignore: |
  ansible_collections/
  inventory/
  my-vars/
  my-logs/
  roles/
  xxx*

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 80
    level: warning
  # Enforce True and False, over true and false
  truthy:
    allowed-values: ["True", "False"]
