---
# Install roles from Ansible Galaxy.
roles:
  # Role for securing the servers
  - name: geerlingguy.security
    version: 2.2.0

  # Role for installing Docker and docker-compose on servers
  - name: geerlingguy.docker
    version: 5.2.1

  # Role for setting up Skynet Webportal
  - name: skynetlabs.skynet_webportal
    src: https://github.com/SkynetLabs/ansible-role-skynet-webportal
    version: v0.0.1-alfa

# Install collections from Ansible Galaxy.
collections:
  # Required for controling Docker containers and docker-compose
  - name: community.docker
    version: 3.1.0

  # Required for LastPass lookups (community.general.lastpass)
  - name: community.general
    version: 5.6.0

  # Required for HashiCorp Vault lookups
  - name: community.hashi_vault
    version: 3.3.0

  # Required e.g. for adding SSH keys (ansible.posix.authorized_key)
  - name: ansible.posix
    version: 1.4.0
