---

# Find primary node in the MongoDB replicaset
# TODO: This ansible playbook task, should be moved to portal role

# This task expects:
# - MongoDB node where we run this task is a member of the replicaset

- name: Reset mongo primary host
  set_fact:
    mongo_primary_host: ""

- name: Get MongoDB replicaset primary member
  include_tasks: tasks/portal-role-task-mongo-shell-eval.yml
  vars:
    mongodb_shell:
      # isMaster.primary returns string in format '<subdomain>.<domain>.<tld>:
      # <port>', we need to extract only the subdomain which is Ansible host or
      # '<domain>.<tld>:<port>' for a single node clusters without subdomain.
      eval: |
        rs.isMaster().primary
      until: True
      retries: 0

- name: Set MongoDB primary host
  set_fact:
    # See the comment in the above task for transformed output contents and the
    # way we parse it.
    mongo_primary_host: >-
      {{
        inventory_hostname
        if ansible_host == portal_domain | default(webportal_common_config.portal_cluster_domain)
        else mongo_shell_result.transformed_output.split('.') | first
      }}

- name: Fail if primary node was not found
  fail:
    msg: "MongoDB Primary host was not found"
  when: mongo_primary_host | default('') == ''

- name: Log MongoDB primary member Ansible host
  debug:
    msg: "MongoDB primary member Ansible host: {{ mongo_primary_host }}"
