---
# Clean Portal sia/renter/renter.log file

# Note: This task should be performed while sia is stopped

- name: Pull Alpine image
  community.docker.docker_image:
    name: alpine:3.15.0
    source: pull

- name: Print timestamp before cleaning renter.log
  debug:
    msg: "{{ inventory_hostname + ' renter.log cleaning start: ' + lookup('pipe','date +%Y-%m-%dT%H:%M:%S') + ' UTC' }}"

# This action cleans the renter log by removing lines with the sed tool in order
# to shrink the log size
#
# NOTE: To update the lines that are pruned, update the renter_log_lines
# variable
- name: Clean renter.log file
  community.docker.docker_container:
    name: clean-renter-logs
    image: alpine:3.15.0
    volumes:
      - "{{ webportal_dir }}/docker/data/sia/renter:/sia-renter"
    command: "sed -i '/{{ item }}/d' /sia-renter/renter.log"
    container_default_behavior: no_defaults
    detach: False
    auto_remove: True
  loop: "{{ renter_log_lines }}"
