---
# Disable health checks and stop docker services

- name: Include checking majority of MongoDB voting members
  include_tasks: tasks/portal-mongo-replicaset-check-majority.yml

- name: Include disabling portal health check
  include_tasks: tasks/portal-health-check-disable.yml

- name: Check for renter accounting issues
  shell: docker exec sia siac renter workers hsj -v | grep insufficient | wc -l
  register: insufficient_balance_workers

- name: Include stopping portal docker services
  include_tasks: tasks/portal-docker-services-stop.yml

- name: Reset accounts.dat when insufficient balance workers point to renter accounting issues
  command: "rm -f {{ sia_data_dir }}/renter/accounts.dat"
  become: True
  when: insufficient_balance_workers.rc == 0 and insufficient_balance_workers.stdout | int > 100

# Below are optional tasks to include via portal-version.yml file
- name: Include cleaning sia renter.log file
  include_tasks: tasks/portal-logs-clean-renter-log.yml
  when: clean_renter_log | default(False)
