---

# Run MongoDB shell command on MongoDB primary host
# TODO: This ansible playbook task, should be moved to portal role

# input:
# - mongodb_shell_delegated:
#   - host
#   - eval
#   - ignore_errors (optional, default: False)
# output: mongo_shell_delegated_result

- debug:
    msg: |
      mongodb_shell_delegated.host: "{{ mongodb_shell_delegated.host }}"
      hostvars[mongodb_shell_delegated.host].ansible_host: "{{ hostvars[mongodb_shell_delegated.host].ansible_host }}"
      login_host: "{{ 'localhost' if (hostvars[mongodb_shell_delegated.host].custom_mongo_port is not defined) else hostvars[mongodb_shell_delegated.host].ansible_host }}"
      login_port: "{{ hostvars[mongodb_shell_delegated.host].custom_mongo_port | default(default_mongo_port | string) }}"
      login_user: "{{ webportal_common_config.skynet_db_user }}"
      login_password: "{{ webportal_common_config.skynet_db_pass }}"
      mongo_cmd: "docker exec mongo mongo"
      db: "{{ mongodb_shell_delegated.db | default(omit) }}"
      eval: "{{ mongodb_shell_delegated.eval }}"
      register: mongo_shell_delegated_result
      delegate_to: "{{ mongodb_shell_delegated.host }}"

- name: Run mongo shell command on MongoDB primary host
  community.mongodb.mongodb_shell:
    # Use secure localhost connection unless on subcrap test cluster
    login_host: "{{ 'localhost' if (hostvars[mongodb_shell_delegated.host].custom_mongo_port is not defined) else hostvars[mongodb_shell_delegated.host].ansible_host }}"
    login_port: "{{ hostvars[mongodb_shell_delegated.host].custom_mongo_port | default(default_mongo_port | string) }}"
    login_user: "{{ webportal_common_config.skynet_db_user }}"
    login_password: "{{ webportal_common_config.skynet_db_pass }}"
    mongo_cmd: "docker exec mongo mongo"
    db: "{{ mongodb_shell_delegated.db | default(omit) }}"
    eval: "{{ mongodb_shell_delegated.eval }}"
    # transformed_output can't be parsed correctly by this module, keep it raw
    transform: raw
  register: mongo_shell_delegated_result
  delegate_to: "{{ mongodb_shell_delegated.host }}"
  vars:
    ansible_port: "{{ hostvars[mongodb_shell_delegated.host].ansible_port | default(default_ssh_port) }}"
  ignore_errors: "{{ mongodb_shell_delegated.ignore_errors | default(False) }}"
