---
# Setup portal ufw firewall rules

- name: Install ufw firewall
  apt:
    update_cache: true
    cache_valid_time: 3600 # 60 minutes
    state: latest
    name: ufw

- block:
    - name: Reset ufw (reset ufw rules and disables ufw firewall)
      community.general.ufw:
        state: reset

    - name: Limit SSH access
      community.general.ufw:
        rule: limit
        direction: in
        port: "{{ default_ssh_port | string }}"
        proto: tcp

    - name: Allow outgoing traffic by default
      community.general.ufw:
        default: allow
        direction: outgoing

    - name: Deny incoming traffic by default
      community.general.ufw:
        default: deny
        direction: incoming

    - name: Allow specific incoming ports
      community.general.ufw:
        rule: allow
        direction: in
        port: "'{{ item }}'"
        proto: tcp
      loop:
        - 80
        - 443
        - 26257
        - 27017
    # Deny outgoing traffic to local network
    - block:
        - name: Allow outgoing traffic to docker local network
          community.general.ufw:
            rule: "allow"
            proto: "any"
            direction: "out"
            to_ip: "{{ item }}"
          loop: "{{ local_networks_allowed }}"

        - name: Deny outgoing traffic to local networks
          community.general.ufw:
            rule: "deny"
            proto: "any"
            direction: "out"
            to_ip: "{{ item }}"
          loop: "{{ local_networks_denied }}"
      when: ufw_deny_outgoing_to_local_network

  # On error set at least SSH rule and enable firewall
  always:
    - name: Limit SSH access
      community.general.ufw:
        rule: limit
        direction: in
        port: "{{ default_ssh_port | string }}"
        proto: tcp

    # Using this setting has a limitation: If the firewall is reloaded manually
    # (not set via this Ansible task), the limit is set back to default values.
    # If this causes issues, this script should be updated.
    - name: Increase SSH limit 10x for scripts
      ansible.builtin.replace:
        path: /etc/ufw/user.rules
        regexp: ^(-A ufw-user-input .* --dport 22 .* )--seconds \d+ --hitcount \d+( -j ufw-user-limit)$
        # Default limit is: --seconds 30 --hitcount 6
        replace: \1--seconds 30 --hitcount 60\2

    - name: Enable Firewall
      community.general.ufw:
        state: enabled
