---
# Check cluster config exists and add it's value to the list

- name: Initialize cluster config paths from and to
  ansible.builtin.set_fact:
    cluster_config_path_from: "{{ cluster_config_list_from[cluster_config_index] }}"
    cluster_config_path_to: "{{ cluster_config_list_to[cluster_config_index] }}"

# Handle destination

- name: Set secrets storage to destination
  set_fact:
    secrets_storage: "{{ hostvars.localhost.secrets_storage_to }}"

- name: Include checking if cluster config record exists
  include_tasks: tasks/secrets-storage-common-check-record-exists.yml
  vars:
    secret_path: "{{ cluster_config_path_to }}"

# Run only on hosts that have existing cluster config record in destination.
# Can't use end_host here, because one host can check multiple cluster configs
# In a loop.
- block:
    - name: Include loading cluster config from destination
      include_tasks: "tasks/secrets-storage-common-load-yaml-or-json.yml"
      loop:
        - secret_path: "{{ cluster_config_path_to }}"
          var_name: "cluster_config_to"

    # Handle source

    - name: Set secrets storage to source
      set_fact:
        secrets_storage: "{{ hostvars.localhost.secrets_storage_from }}"

    - name: Include loading cluster config from source
      include_tasks: "tasks/secrets-storage-common-load-yaml-or-json.yml"
      loop:
        - secret_path: "{{ cluster_config_path_from }}"
          var_name: "cluster_config_from"

    # Handle if source/destination cluster configs are different

    - name: Check source and destination cluster configs
      vars:
        original_dict: "{{ cluster_config_from }}"
        new_dict: "{{ cluster_config_to }}"
      include_tasks: tasks/dictionary-diff.yml

    - name: Log differences when a destination cluster config is not synced with source
      debug:
        msg: |
          The following host has different cluster configs between source and destination:

          HOST: {{ inventory_hostname }}
          FROM {{ hostvars.localhost.secrets_storage_from }}: {{ cluster_config_path_from }}
          TO {{ hostvars.localhost.secrets_storage_to }}: {{ cluster_config_path_to }}

          {{ diff_string }}
      when: different_dict

    - name: Add cluster config that is not synced between source and destination
      ansible.builtin.set_fact:
        cluster_configs_different: >-
          {{
            cluster_configs_different
            +
            [{'from': cluster_config_path_from, 'to': cluster_config_path_to}]
          }}
      when: different_dict
  when: secrets_storage_record_exists
