---
# Load user credentials from secrets storage to ansible_become_pass

- name: Check hosts.ini in ansible-private repository was updated for playbooks v2
  ansible.builtin.assert:
    that:
      - ansible_become_pass is not defined
      - webportal_user_pass_hash is not defined
    fail_msg: |
      Ansible Playbooks v2 require update of hosts.ini file in ansible-private
      repository.
      Please read portal documentation how to update the hosts.ini file.

      E.g. the following variables
      - ansible_become_pass
      - webportal_user_pass_hash
      
      should not be defined in hosts.ini (should be removed).
