---
# Save secret data to yaml or json record in secrets storage

- name: Set secret path extension
  set_fact:
    secret_path_extension: "{{ secret_path.split('.') | last }}"

- name: Assert secret data was passed correctly
  ansible.builtin.assert:
    that:
      - secret_path is defined
      - secret_path != ''
      - secret_path_extension == 'yml' or secret_path_extension == 'json'
      - secret_data is defined
      - secret_data != 'undefined'

# Handle formatting a yaml data to string
- block:
    - block:
        # Handle formatting mongo_db_mgkey in yaml
        #
        # In case default yaml formatting is used for mongo_db_mgkey, yaml record
        # in secrets storage becomes hard to read like:
        #
        # some_key: some_value
        # mongo_db_mgkey: very...long...string...
        # spread...over...jhgjgjhgjhgjhgjhgjhgjhg
        # multiple...jgfgdfdytrytoiuyiuuytuytuyty
        # lines...uytuytuytuytuytuytuytuytuytuiyt
        # in...yaml...record...uyrhvnjfsrewkhljhk
        # some_other_key: some_other_value
        #
        # The following block formats (i.e. indents) mongo_db_mgkey the following
        # way:
        #
        # some_key: some_value
        # mongo_db_mgkey: |
        #   very...long...string...
        #   spread...over...jhgjgjhgjhgjhgjhgjhgjhg
        #   multiple...jgfgdfdytrytoiuyiuuytuytuyty
        #   lines...uytuytuytuytuytuytuytuytuytuiyt
        #   in...yaml...record...uyrhvnjfsrewkhljhk
        # some_other_key: some_other_value
        #
        # In order to do it this way, we generate yaml string with a dummy
        # mongo_db_mgkey using default formatting and then we replace
        # dummy mongo_db_mgkey value with a correct value using an indented string.

        - name: Store indented mongo mgkey to temporary variable
          vars:
            prefix: "  "
          set_fact:
              # Add prefix to each mgkey line (indent each mgkey line).
              # NOTE: the weird use of the `join()` statement is for formatting.
              # The newline character `\n` isn't recognized in this type of
              # multiline string
            indented_mgkey: >-
              {{
                [prefix]
                | product(secret_data.mongo_db_mgkey.splitlines())
                | map('join')
                | list
                | join(newline_char)
              }}

        - name: Created secret data dummy with a dummy mongo mgkey value
          set_fact:
            secret_data_dummy: >-
              {{ secret_data
              | combine({'mongo_db_mgkey': 'dummy'}) }}

        # Create secret data yaml string with a dummy mgkey value using default
        # yaml formatting and then replace mgkey with an actual value using
        # indented string.
        - name: Create yaml string (if mongo db mgkey is defined)
          set_fact:
            secret_data_yaml_string: >-
              {{
                secret_data_dummy
                | to_nice_yaml(width=2048)
                | replace(
                    'mongo_db_mgkey: dummy',
                    'mongo_db_mgkey: |' + newline_char + indented_mgkey
                  )
              }}
      when: secret_data.mongo_db_mgkey is defined

    - name: Create yaml string (if mongo db mgkey is not defined)
      set_fact:
        secret_data_yaml_string: >-
          {{
            secret_data
            | to_nice_yaml(width=2048)
          }}
      when: secret_data.mongo_db_mgkey is not defined
  when: secret_path_extension == 'yml'

# We need to format json data to string at the time of saving as it is loaded
# back as data (not json string) on each Ansible assignment.
- name: Set secret string to format according to secret path extension
  set_fact:
    secret_string_formatted: >-
      {{
        secret_data_yaml_string
        if secret_path_extension == 'yml'
        else secret_data
      }}

- name: Include saving secret string to secrets storage
  include_tasks: "tasks/secrets-storage-common-save-string-to-yaml-or-json.yml"
  vars:
    save_string_secret_path: "{{ secret_path }}"
    secret_string: "{{ secret_string_formatted }}"

- name: Reset passed secret path and data
  set_fact:
    secret_path: ''
    secret_data: 'undefined'
