---
# Migrate cluster config

# Read from source

- name: Set secrets storage to source
  set_fact:
    secrets_storage: "{{ hostvars.localhost.secrets_storage_from }}"

- name: Include loading cluster config from source
  include_tasks: "tasks/secrets-storage-common-load-yaml-or-json.yml"
  loop:
    - secret_path: "{{ cluster_config_to_migrate.from_to.from }}"
      var_name: cluster_config_data_from

# Write to destination

- name: Set secrets storage to destination
  set_fact:
    secrets_storage: "{{ hostvars.localhost.secrets_storage_to }}"

- name: Include saving cluster config data to destination
  include_tasks: "tasks/secrets-storage-common-save-data-to-yaml-or-json.yml"
  vars:
    secret_path: "{{ cluster_config_to_migrate.from_to.to }}"
    secret_data: "{{ cluster_config_data_from }}"