---
# Save secret string to yaml or json record in secrets storage

- name: Set secret path extension
  set_fact:
    secret_path_extension: "{{ save_string_secret_path.split('.') | last }}"

- name: Assert secret string was passed correctly
  ansible.builtin.assert:
    that:
      - save_string_secret_path is defined
      - save_string_secret_path != ''
      - secret_string is defined
      - secret_string != 'undefined'
      - secret_path_extension == 'yml' or secret_path_extension == 'json'

- name: Include saving string to yaml to secure storage
  include_tasks: "tasks/secrets-storage-{{ secrets_storage }}-save-string-to-yaml-or-json.yml"

- name: Reset passed secret path and data
  set_fact:
    save_string_secret_path: ''
    secret_string: 'undefined'
