---
# Save secret string to yaml or json record in plaintext

- name: Include checking plaintext secrets directory
  include_tasks: tasks/secrets-storage-plaintext-check-secrets-dir.yml

- name: Ensure plaintext storage directory/subdirectories exist
  ansible.builtin.file:
    path: "{{ plaintext_base_dir + '/' + save_string_secret_path | dirname }}"
    state: directory
    owner: "{{ plaintext_secrets_uid }}"
    group: "{{ plaintext_secrets_gid }}"
    mode: "{{ plaintext_secrets_mode }}"
    follow: True
  delegate_to: localhost

- name: Write secret data to yaml or json record in plaintext secrets storage
  vars:
    # Create shorter variable names to shorten content oneliner.
    yaml_string: "{{ secret_string | replace('\\n', newline_char) }}"
    is_yaml: "{{ secret_path_extension == 'yml' }}"
    ss: "{{ secret_string }}"
  ansible.builtin.copy:
    # Multi-line mgkey variable is formatted in a specific way. Here we
    # need to adjust the formatting for saving to plaintext secrets storage.
    # We can't format json string earlier as it is loaded to Ansible vars
    # as data (not a json string) so we format it at the time of saving.
    # To keep nice json format we need to use `content` oneliner, because
    # multiline definitions break json nice formatting.
    content: "{{ yaml_string if is_yaml else (ss | to_nice_json(indent=2)) }}"
    dest: "{{ plaintext_base_dir }}/{{ save_string_secret_path }}"
    owner: "{{ plaintext_secrets_uid }}"
    group: "{{ plaintext_secrets_gid }}"
    mode: "{{ plaintext_secrets_mode }}"
    directory_mode: "{{ plaintext_secrets_mode }}"
    follow: True
  delegate_to: localhost
  no_log: True
