---
# Save webportal user credentials to HashiCorp Vault

- name: Include checking if user credentials record exists in HashiCorp Vault
  include_tasks: tasks/secrets-storage-hashicorp-vault-check-record-exists.yml
  vars:
    secret_path: "{{ hashicorp_vault_portal_credentials_server }}"

# Create and save webportal user credentials to HashiCorp Vault (if missing in HashiCorp Vault)
- block:
    - name: Set webportal user password
      set_fact:
        ansible_become_pass: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"

    - name: Save webportal user credentials to HashiCorp Vault record
      community.hashi_vault.vault_write:
        url: "{{ hashicorp_vault_url }}"
        path: "{{ hashicorp_vault_portal_credentials_server_incl_backend_dir }}"
        token: "{{ hashicorp_vault_token }}"
        token_validate: True
        data:
          data:
            username: "{{ webportal_user }}"
            password: "{{ ansible_become_pass }}"
      delegate_to: localhost
      no_log: True
  when: not secrets_storage_record_exists
