---
# Load yaml or json secure note from plaintext to Ansible variable

- name: Include checking if record exists in plaintext secrets storage
  include_tasks: tasks/secrets-storage-plaintext-check-record-exists.yml
  vars:
    secret_path: "{{ load_item.secret_path }}"

- block:
    - name: Read yaml or json plaintext record
      ansible.builtin.slurp:
        path: "{{ plaintext_base_dir }}/{{ load_item.secret_path }}"
      delegate_to: localhost
      register: plaintext_record_slurped

    - name: Parse user credentials plaintext record
      set_fact:
        secrets_storage_data: "{{ plaintext_record_slurped['content'] | b64decode }}"
  when: secrets_storage_record_exists
