---
# Check if secret exists in LastPass

- name: Check if LastPass server record exists
  local_action:
    module: ansible.builtin.command
    cmd: "lpass ls --sync now '{{ secret_path }}'"
  register: lastpass_ls_result

- name: Set secret exists flag
  set_fact:
    secrets_storage_record_exists: "{{ lastpass_ls_result.stdout_lines | length != 0 }}"
