---
# Check if secret exists in plaintext

- name: Check if server record exists in plaintext
  ansible.builtin.stat:
    path: "{{ plaintext_base_dir }}/{{ secret_path }}"
    follow: True
  delegate_to: localhost
  register: plaintext_stat_secret_result

- name: Set secret exists flag
  set_fact:
    secrets_storage_record_exists: "{{ plaintext_stat_secret_result.stat.exists }}"
