---
# Save webportal user credentials to secrets storage

- name: Include saving user credentials to secrets storage
  include_tasks: "tasks/secrets-storage-{{ secrets_storage }}-save-user-credentials.yml"
