---
# Check plaintext secrets directory exists inside ansible-private directory

- name: Check plaintext secrets directory exists in ansible-private directory
  ansible.builtin.stat:
    path: "{{ plaintext_base_dir }}/{{ plaintext_ansible_dir }}"
    follow: True
  delegate_to: localhost
  register: plaintext_ansible_dir_stat_result

- name: Fail if ansible directory doesn't exist inside ansible-private directory
  fail:
    msg: |
      Directory:
        {{ plaintext_ansible_dir }}
      doesn't exist.

      To use plaintext secrets storage plaintext secrets directory:
        {{ plaintext_secrets_dir }}
      must exist inside your ansible-private directory.
  when: not plaintext_ansible_dir_stat_result.stat.exists

- name: Get plaintext secrets directory owner, group and permissions
  set_fact:
    plaintext_secrets_uid: "{{ plaintext_ansible_dir_stat_result.stat.uid }}"
    plaintext_secrets_gid: "{{ plaintext_ansible_dir_stat_result.stat.gid }}"
    plaintext_secrets_mode: "{{ plaintext_ansible_dir_stat_result.stat.mode }}"
