---
# Save secret string to yaml or json record in LastPass

- name: Add or edit secret data to yaml record in LastPass
  local_action:
    module: shell
    # We can't format json string earlier as it is loaded to Ansible vars as
    # data (not a json string) so we format it at the time of saving.
    cmd: printf '{{ secret_string if (secret_path_extension != 'json') else (secret_string | to_nice_json(indent=2)) }}' | lpass {{ secret_add_or_edit_command }} --sync now --notes --non-interactive '{{ save_string_secret_path }}'
  no_log: True
