---
# Save secret string to yaml or json record in HashiCorp Vault

- name: Write secret data to yaml record in HashiCorp Vault
  community.hashi_vault.vault_write:
    url: "{{ hashicorp_vault_url }}"
    path: "{{ hashicorp_vault_storage_backend_dir }}/{{ save_string_secret_path }}"
    token: "{{ hashicorp_vault_token }}"
    token_validate: True
    data:
      data:
        # Multi-line mgkey variable is formatted in a specific way. Here we
        # need to adjust the formatting for saving to HashiCorp Vault yaml.
        yml: "{{ secret_string | replace('\\n', newline_char) }}"
  delegate_to: localhost
  no_log: True
  when: secret_path_extension == 'yml'

- name: Write secret data to json record in HashiCorp Vault
  community.hashi_vault.vault_write:
    url: "{{ hashicorp_vault_url }}"
    path: "{{ hashicorp_vault_storage_backend_dir }}/{{ save_string_secret_path }}"
    token: "{{ hashicorp_vault_token }}"
    token_validate: True
    data:
      data:
        # We can't format json string earlier as it is loaded to Ansible vars
        # as data (not a json string) so we format it at the time of saving.
        json: "{{ secret_string | to_nice_json(indent=2) }}"
  delegate_to: localhost
  no_log: True
  when: secret_path_extension == 'json'
