---
# Load user credentials from Lastpass to ansible_become_pass

- name: Check user credentials exist in LastPass
  set_fact:
    user_credentials_exist: "{{ lookup('pipe', 'lpass ls ' + lastpass_portal_credentials_server) != '' }}"

- name: Load user credentials from Lastpass
  set_fact:
    ansible_become_pass: "{{ lookup('community.general.lastpass', lastpass_portal_credentials_server, field='password') }}"
  when: user_credentials_exist

- name: Fail if user credentials do not exist in LastPass
  fail:
    msg: |
      Requested user credentials doesn't seem to exist in LastPass:
      - Ansible host: {{ inventory_hostname }}
      - LastPass path: {{ lastpass_portal_credentials_server }}
  when: not user_credentials_exist
