---
# Check if secret exists in secrets storage

- name: Assert secret path was passed to this task
  ansible.builtin.assert:
    that:
      - secret_path is defined
      - secret_path != ''

- name: Include checking record exists in secrets storage
  include_tasks: "tasks/secrets-storage-{{ secrets_storage }}-check-record-exists.yml"

- name: Set secret command to `add` or `edit` and reset secret path
  set_fact:
    secret_add_or_edit_command: "{{ 'edit' if secrets_storage_record_exists else 'add' }}"
    # Reset secret path so that next call to this included task has to set it
    # explicitly (not using a leftover from the previous call)
    secret_path: ''
