# This config file can be used to set any ansible variables needed to execute
# necessary ansible playbooks. These settings when used will also override
# values defined in playbooks/group_vars/webportals.yml.

###############################################################################
# OPTIONAL
#
# Below are a list of variables that are optional depending on the playbook you
# are running.
###############################################################################

# Deploying a custom website for your portal is supported by defining a
# dockerfile for your website.
#
# The custom website dockerfile can be defined in the following ways:
#
# If you have a simple repo with a Dockerfile at the root level, you simply
# define a website_custom_build variable that is the https git url with a target
# branch defined.
# website_custom_build: https://github.com/user/website-repo.git#main
#
# or
#
# If you have a repo where the Dockerfile is not at the root level, you will
# need to define a website_custom_build_context which is the https git url with
# a target branch defined and a website_custom_build_dockerfile which is the
# relative path to the dockerfile in the repository.
# website_custom_build_context: https://github.com/user/website-repo.git#main
# website_custom_build_dockerfile: ./path/to/Dockerfile
#
# If you need to define a custom website dockerfile, simply uncomment and define
# the variables you need based on the above options.
# website_custom_build:
# website_custom_build_context:
# website_custom_build_dockerfile:

# Custom docker images.
#
# If you want to override a docker image for a specific service, you can do so
# by defining the service and image in the docker_image_overrides variable.
#
# docker_image_overrides:
#   - { service: "website", image: "skynetlabs/website-skynetpro-net" }
#   - { service: "blocker", image: "skynetlabs/blocker" }

# Set the skynet-webportal version by entering a git branch, git tag or git
# commit.
portal_repo_version: "..."
