---

hashicorp_vault:
  dir: "/home/{{ ansible_user }}/hashicorp-vault"
  domain: "vault.siasky.dev" # Set your domain here

# Traefik settings
traefik:
  api:
    dashboard: false # default: false
    insecure: false # default: false
  ssl:
    email: "devs@skynetlabs.com" # Set your email here
