---
# Install Docker
# This role is expected to be executed with root permissions

- name: Install Docker
  hosts: all
  gather_facts: True

  # Limit concurrency
  serial: 1

  # Stop on first error, do not execute on the next host
  any_errors_fatal: True

  # Playbook specific vars
  vars:
    max_hosts: 1

  tasks:
    # Check '--limit' is used
    - name: Fail if you are targeting more than 1 hosts
      include_tasks: tasks/host-limit-check.yml
      run_once: True

    - name: Include checking server OS compatibility
      include_tasks: tasks/check-server-os-compatibility.yml

    # Ensure docker group
    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: "docker"
        state: present

    # Install Docker
    - name: Include role to install Docker
      include_role:
        name: geerlingguy.docker
